name = "ace-website"
compatibility_date = "2024-12-01"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "ace-leads"
database_id = "19643c50-edef-4196-aeab-9e2db657fc9d"

[vars]
PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAAC1egCP_ntt5kef_"
# TURNSTILE_SECRET_KEY is set via Cloudflare dashboard secrets
TURNSTILE_SECRET_KEY = ""
